name: Quality Gate CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-quality:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les Tests Unitaires
        run: npm test
    
  build-docker:
    needs: check-quality 
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build de l'image Docker
        run: |
          docker build -t mon-app-devops:${{ github.sha }} .
      
  deploy:
    needs: build-docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: +Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}